update=11/28/2017 4:27:03 PM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[general]
version=1
[eeschema]
version=1
LibDir=
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/LilyPad-Wearables
LibName31=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-Aesthetics
LibName32=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-Batteries
LibName33=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-Boards
LibName34=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-Capacitors
LibName35=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-Clocks
LibName36=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-Coils
LibName37=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-Connectors
LibName38=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-DiscreteSemi
LibName39=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-Displays
LibName40=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-Electromechanical
LibName41=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-Fuses
LibName42=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-GPS
LibName43=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-Hardware
LibName44=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-IC-Amplifiers
LibName45=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-IC-Comms
LibName46=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-IC-Conversion
LibName47=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-IC-Logic
LibName48=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-IC-Memory
LibName49=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-IC-Microcontroller
LibName50=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-IC-Power
LibName51=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-IC-Special-Function
LibName52=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-Jumpers
LibName53=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-LED
LibName54=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-PowerSymbols
LibName55=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-Resistors
LibName56=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-RF
LibName57=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-Sensors
LibName58=C:/Users/Nick/Documents/SparkX/KiCAD Stuff/SparkFun-Libraries/SparkFun-KiCad-Libraries-master/SparkFun-Switches
